### ISSUE TITLE
coupled system for derivatives

### ISSUE THREAD

**Issue by tpapp** [SciML/DiffEqBayes.jl#85]
While reading [The Stan Math Library: Reverse-Mode Automatic Differentiation in C++](https://arxiv.org/abs/1509.07164) (specifically, Section 13) I noticed that Stan used a coupled system instead of ADing through the solver, which they claim is worse.

I am wondering if this would make sense for this package, or if it is feasible to implement.

**Comment by ChrisRackauckas** [comment]
See https://arxiv.org/abs/1812.01892 . 

Their paper is just incorrect here since they are using a computational graph approach. "Large expression graph" doesn't make sense if it's a code generation approach. Secondly, you can control the error when using AD via extended arithmetic just by defining a new norm which incorporates the partial terms (for example, define `internalnorm = ...` which uses the dual partials in DifferentialEquations.jl). 

The real reason they didn't do it is because they don't have any good integrators which can be fully auto-diff'd... just a simple Dormand-Prince (without the dopri adaptivity) method. So they said you can't autodiff integrators well, and showed the forward sensitivity analysis calculation. Forward sensitivity analysis is actually equivalent to forward-mode automatic differentiation applied to the integrator with time not being a dual number (this isn't hard to prove, look at the equation) under some choice of adaptivity norm (which is chosen to be the default in DiffEq under the presence of dual numbers: https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/init.jl#L22-L28). However, if you do this via AD, then you will actually allow the compiler to do everything fully sparse and SIMD the calculation of the `f` and its primal, meaning that it ends up being a more performant implementation, which is what we show in the paper.

Additionally, the reason why forward-mode AD is faster in the cases generally done with Bayesian estimation is because forward sensitivity is cheaper when the number of ODE parameters is low, which is usually all Bayesian can be applied for (since it gets expensive!). The analogue to reverse-mode AD is adjoint sensitivity analysis, which yes implementations of adjoint sensitivity analysis are much faster than tape-based, and still a little faster than source-to-source ADs since you can handle the adaptivity more directly.

All of these methods are implemented in DifferentialEquations.jl already (in DiffEqSensitivity.jl) and the documentation is at http://docs.juliadiffeq.org/latest/analysis/sensitivity.html . I hope we can get a better API in the future to allow a choice between the different modes (by defining a complex Zygote `adjoint` and allowing the user to pass a keyword argument that it dispatches on when lowering to the adjoint call), but for most problems people are using this library for, forward-mode AD is the most appropriate so we just let the Bayesian library choose the AD since they default to ForwardDiff (at least they used to, that might've changed).

**Comment by tpapp** [comment]
I really appreciate the explanation. I am revamping TransformVariables.jl now to work with Zygote, so the DiffEq ecosystem supports it it should be as easy as `ADgradient(:Zygote, ...)` to pick it.

**Comment by ChrisRackauckas** [comment]
Solved by using `concrete_solve`.
